version: '3.3'

volumes:
  pg_data_production:
  static_production:
  media_production:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    image: temamx/foodgram-project-react-backend
    env_file: .env
    restart: always
    volumes:
      - static_production:/app/static/
      - media_production:/app/media/
    depends_on:
      - db
  frontend:
    image: temamx/foodgram-project-react-frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_production:/var/html/media/
      - static_production:/var/html/static/
    depends_on:
      - backend